security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        admin:
            entity: { class: AppBundle:User }
        secured_area_provider:
            id: ehub.oauth.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            provider:   admin
            anonymous:  ~
            form_login:
                login_path: /login
                check_path: /login_check
                success_handler: app.authentication.success_handler
            logout:
                path:   /logout
                target: /login
            #anonymous: ~
            oauth:
                resource_owners:
                    facebook:     "/login/check-facebook"
                    twitter:      "/login/check-twitter"
                    google:       "/login/check-google"
                login_path:   /login
                use_forward:  false
                failure_path: /login
                oauth_user_provider:
                    service: ehub.oauth.user_provider

    access_control:
      - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, roles: IS_AUTHENTICATED_FULLY }