
# authentication
default_security_target:
    pattern:  /
    defaults: { _controller: AppBundle:Default:index }

login:
    pattern:  /login
    defaults: { _controller: AppBundle:Auth:login }

login_check:
    pattern:  /login_check

logout:
    path:   /logout


# admin
admin_user_index:
    pattern:  /admin/user
    defaults: { _controller: AppBundle:User:index }

admin_user_add:
    pattern:  /admin/user/add
    defaults: { _controller: AppBundle:User:add }

admin_user_edit:
    pattern:  /admin/user/edit/{id}
    defaults: { _controller: AppBundle:User:edit }

admin_user_switch_active:
    pattern:  /admin/user/switch-active/{id}
    defaults: { _controller: AppBundle:User:switchActive }


# password
user_password_reset_email:
    pattern:  /password/email
    defaults: { _controller: AppBundle:Password:email }

user_password_reset:
    pattern:  /password/reset/{passwordResetKey}
    defaults: { _controller: AppBundle:Password:reset }
    requirements:
        passwordResetKey: "[a-zA-Z0-9]{32}"

user_password_reset_response:
    pattern:  /password/success
    defaults: { _controller: AppBundle:Password:resetResponse }


# general
user_info:
    pattern:  /user/{id}
    defaults: { _controller: AppBundle:Default:userInfoAction }
    requirements:
        id:  \d+