services:

    app.authentication.success_handler:
        class: AppBundle\Service\Authentication\AuthenticationSuccessHandler
        public: false
        arguments:  [@router, @doctrine.orm.default_entity_manager]

    app.mail:
        class: AppBundle\Service\Mail
        arguments:  [%mailgun_api_key%, %mailgun_domain%]

    ehub.oauth.user_provider:
        class: AppBundle\Security\OAuthUserProvider
        arguments: ["@doctrine.orm.entity_manager", "@security.encoder_factory"]